services:
  unitn-ap-api-dev:
    image: ghcr.io/unitn-ap-2025/api-dev
    container_name: unitn-ap-api-dev
    working_dir: /workspace
    env_file:
      - .dev.env
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        exec sleep infinity
      "